### ISSUE TITLE
Hi! I just watched nearly all technical videos on your YouTube channel. May I have the nice PPT template that you frequently use? Thanks!

### ISSUE THREAD

**Issue by yingqichao** [FanChiMao/SRMNet#2]
Hi Dear Dr. Fan

Both your presentations and the PPTs are so wonderful. Could you share the PPT template with me for my class presentation? Thanks a lot if you could share! I will not leak it to anyone else~
https://www.youtube.com/watch?v=0hHZ054rGpY

My email is shinydotcom@163.com and I am a phd grade 1 student from Fudan University. Sincerely.

**Comment by FanChiMao** [comment]
Thanks for your affirmation again. 😄 
I am glad to share my PPT template, and have sent to you by the mail. 👍🏼
